name: firebase_authentication_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  lottie: ^1.4.1

  google_fonts: ^2.3.2

  # Provider State Management.
  provider: ^6.0.4

  # Firebase Database
  firebase_core: ^2.3.0

  # Add Authentication
  firebase_auth: ^4.1.5

  # Firebase Crashlytics
  firebase_crashlytics: ^3.0.6

  # Snackbar
  another_flushbar: ^1.10.29

  # GetIt
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/