name: firebase_authentication_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  # Provider State Management 
  provider: ^6.0.4
  logger: ^1.1.0

  # Firebase Database
  firebase_core: ^2.3.0

  # Add Authentication such as Google-SignIn..
  firebase_auth: ^4.1.5
  firebase_crashlytics: ^3.0.6

  # Snackbar
  another_flushbar: ^1.10.29

  # GetIt
  get_it: ^7.2.0

  # Online Database for Data
  # cloud_firestore: ^3.1.15

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true